In [1]:
import os
import time
import copy
import numpy as np
import pandas as pd
import seaborn as sn
from tqdm import tqdm
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

import sklearn
from sklearn.manifold import TSNE, LocallyLinearEmbedding, Isomap, MDS, SpectralEmbedding
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Function

from models import *
from utils import *
from datasets import *

In [2]:
pref_weights = torch.tensor([ 0.0130, -0.0251,  0.0032,  0.0012,  0.0337,  0.0301, -0.0170, -0.0064, 0.0023])
pref_weights

tensor([ 0.0130, -0.0251,  0.0032,  0.0012,  0.0337,  0.0301, -0.0170, -0.0064,
         0.0023])

In [5]:
pref_weights.softmax(dim=0)

tensor([0.1121, 0.1079, 0.1110, 0.1108, 0.1145, 0.1140, 0.1088, 0.1100, 0.1109])

In [6]:
(pref_weights - torch.mean(pref_weights)) / torch.std(pref_weights)

tensor([ 0.4665, -1.4843, -0.0353, -0.1377,  1.5264,  1.3421, -1.0696, -0.5268,
        -0.0814])

In [16]:
torch.sign(pref_weights) * (torch.abs(pref_weights).softmax(dim=0))

tensor([ 0.1109, -0.1123,  0.1098,  0.1096,  0.1132,  0.1128, -0.1114, -0.1102,
         0.1097])